version: "3.8"

services:
  iot-kafka-emulator:
    container_name: iot-kafka-emulator
    build: '.'
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - KAFKA_TOPIC_NAME=sample_topic
      - KAFKA_BATCH_SIZE=20000
      - KAFKA_BATCH_INTERVAL=500
      - THREAD_NUMBER=1000
      - RUST_BACKTRACE=full
      - DATA_SOURCE=jsonl
    volumes:
      - ./test-data/test.jsonl:/app/data/jsonl/test.jsonl
      - ./test-data/test.jsonl:/app/data/jsonl/test/test.jsonl
  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.4.0'
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'